### ISSUE TITLE
Support for setting server address/port

### ISSUE THREAD

**Issue by shauntarves** [unixsurfer/haproxytool#6]
It looks like haproxyadmin has added support(https://github.com/unixsurfer/haproxyadmin/pull/13) for setting a server address/port, but this tool does not yet offer the option from the CLI.

As haproxy itself now advocates the use of `server-template` for dynamic back-ends (https://www.haproxy.com/blog/dynamic-scaling-for-microservices-with-runtime-api/), it's crucial to be able to programmatically set a server's address.

**Comment by unixsurfer** [comment]
I am actually working on this right now. I need to finish a few things in haproxyadmin and then I will add support for address/port adjustments in haproxytool
